### ISSUE TITLE
Issue with setup.py

### ISSUE THREAD

**Issue by tessadgreen** [manoharan-lab/structural-color#22]
Trying to run setup.py gets me the following error: 

usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

I created a clone of the infer_structcolor repository and copied the package into that, which means that the tests are now running for me, but now I think if this structural-color package is modified won't get the changes (and also maybe makes updating the inference package from github cludgy). There's probably a way to set up Github so it will nest the two (maybe? I'm really not sure). It'd be great to get a bit more instruction on alternate installation in the readme or install files.

**Comment by vnmanoharan** [comment]
Team: you could look into [submodules](https://github.com/blog/2104-working-with-submodules).

**Comment by barkls** [comment]
@tessadgreen I believe that error occurs if you type 'python setup.py', instead of 'python setup.py install' when installing a package, but I'm glad you found a workaround. We agree that we need a better way of interfacing and installing the two packages. Submodules look promising. Thanks for the tip @vnmanoharan!
